import { getMessage, hkdf, signHmac } from "@repo/crypto";
import { fromString, toBase64 } from "@repo/util";

export type SignedSessionHeaders = {
  sessionId: string;
  timestamp: string;
  signature: string;
  nonce: string;
};

/**
 * Derive the same authKey the real client + server derive after a successful OPAQUE login.
 *
 *   sessionSecret = HKDF(sessionKey, "sessionSecret")
 *   authKey       = HKDF(sessionSecret, "sessionAuth", authSalt)
 */
export async function deriveAuthKey(sessionKey: string, authSalt: Uint8Array): Promise<Uint8Array> {
  const sessionSecret = await hkdf(fromString(sessionKey), "sessionSecret");
  return await hkdf(sessionSecret, "sessionAuth", authSalt);
}

/**
 * Produce the four header strings the auth-middleware expects, given a real authKey,
 * an input payload, and the procedure path/type the client is about to call.
 * A fresh nonce is generated by default; tests that simulate a replay must pass an
 * explicit `nonce` so the same value is reused across calls.
 */
export async function signRequest(opts: {
  authKey: Uint8Array;
  sessionId: string;
  type: "mutation" | "query" | "subscription";
  path: string;
  input: Record<string, unknown> | string | undefined;
  /** ms since epoch — defaults to now */
  timestamp?: number;
  /** Override the auto-generated nonce — only set when intentionally replaying. */
  nonce?: string;
}): Promise<SignedSessionHeaders> {
  const timestamp = String(opts.timestamp ?? Date.now());
  const nonce = opts.nonce ?? crypto.randomUUID();
  const message = getMessage(
    opts.type,
    opts.path,
    timestamp,
    nonce,
    (opts.input ?? undefined) as unknown as Record<string, string>,
  );
  const sig = await signHmac(opts.authKey, message);
  return {
    sessionId: opts.sessionId,
    timestamp,
    signature: toBase64(sig),
    nonce,
  };
}
