// Generated by scripts/bundle-migrations.ts from ./drizzle. Do not edit;
// run `pnpm --filter @repo/store migrations:generate` instead.

export const GENERATED_MIGRATIONS: readonly { name: string; statements: readonly string[] }[] = [
  {
    "name": "20261001152327_baseline",
    "statements": [
      "CREATE TABLE `key_material` (\n\t`key` text PRIMARY KEY,\n\t`value` text NOT NULL\n);",
      "CREATE TABLE `records` (\n\t`recordId` text NOT NULL,\n\t`encryptedData` text NOT NULL,\n\t`encryptionNonce` text NOT NULL,\n\t`cryptoVersion` integer DEFAULT 1 NOT NULL,\n\t`version` integer DEFAULT 1 NOT NULL,\n\t`clientUpdatedAt` text NOT NULL,\n\t`created_at` text,\n\t`updated_at` text,\n\t`deleted_at` text,\n\tCONSTRAINT `records_pk` PRIMARY KEY(`recordId`, `version`)\n);",
      "CREATE TABLE `sync_meta` (\n\t`key` text PRIMARY KEY,\n\t`value` text NOT NULL\n);"
    ]
  },
  {
    "name": "20261001173233_vault_keys",
    "statements": [
      "CREATE TABLE `vaults` (\n\t`vaultId` text PRIMARY KEY,\n\t`kind` text NOT NULL,\n\t`keyVersion` integer NOT NULL,\n\t`encryptedVaultKey` text NOT NULL,\n\t`vaultKeyEncryptionNonce` text NOT NULL\n);"
    ]
  }
];
