// Generated by scripts/bundle-migrations.ts from ./drizzle-registry. Do not edit;
// run `pnpm --filter @repo/store migrations:generate` instead.

export const GENERATED_MIGRATIONS: readonly { name: string; statements: readonly string[] }[] = [
  {
    "name": "20261008060745_profile_registry",
    "statements": [
      "CREATE TABLE `profiles` (\n\t`profileId` text PRIMARY KEY,\n\t`mode` text NOT NULL,\n\t`email` text,\n\t`userId` text UNIQUE,\n\t`name` text,\n\t`databaseName` text NOT NULL UNIQUE,\n\t`createdAt` text NOT NULL,\n\t`lastUsedAt` text NOT NULL\n);",
      "CREATE TABLE `registry_meta` (\n\t`key` text PRIMARY KEY,\n\t`value` text NOT NULL\n);",
      "CREATE INDEX `profiles_email_idx` ON `profiles` (`email`);"
    ]
  },
  {
    "name": "20261008185230_last_export",
    "statements": [
      "ALTER TABLE `profiles` ADD `lastExportAt` text;"
    ]
  }
];
