import { type InferSelectModel, sql } from "drizzle-orm";
import {
  index,
  integer,
  pgTable,
  primaryKey,
  timestamp,
  uniqueIndex,
  varchar,
} from "drizzle-orm/pg-core";
import { timestamps } from "../utils/columns.helpers";
import { usersTable } from "./users";

/**
 * A vault groups records under one key (ADR 0001 D6). Ids are generated by the
 * client, so a vault can be created offline.
 */
export const vaultsTable = pgTable(
  "vaults",
  {
    vaultId: varchar().primaryKey(),

    ownerId: varchar()
      .notNull()
      .references(() => usersTable.userId, { onDelete: "cascade" }),

    kind: varchar({ enum: ["personal", "shared"] }).notNull(),
    // Bumped by a key rotation; members' wraps carry the version they hold.
    keyVersion: integer().notNull().default(1),

    // Name, icon, colour: encrypted with the vault key (AAD: vaultId).
    encryptedMeta: varchar().notNull(),
    metaEncryptionNonce: varchar().notNull(),

    ...timestamps,
  },
  (table) => [
    index("vaults_owner_idx").on(table.ownerId),
    // Exactly one personal (default) vault per user.
    uniqueIndex("vaults_one_personal_per_owner_idx")
      .on(table.ownerId)
      .where(sql`${table.kind} = 'personal' AND ${table.deleted_at} IS NULL`),
  ],
);

/**
 * A user's access to a vault. `encryptedVaultKey` is the vault key wrapped
 * under that member's account key (AAD: vaultId + keyVersion). Only `active`
 * members get access; `pending` is an invite not yet accepted (ADR 0001 D7).
 */
export const vaultMembersTable = pgTable(
  "vault_members",
  {
    vaultId: varchar()
      .notNull()
      .references(() => vaultsTable.vaultId, { onDelete: "cascade" }),
    userId: varchar()
      .notNull()
      .references(() => usersTable.userId, { onDelete: "cascade" }),

    role: varchar({ enum: ["owner", "manage", "write", "read"] }).notNull(),
    status: varchar({ enum: ["active", "pending"] })
      .notNull()
      .default("active"),

    keyVersion: integer().notNull(),
    encryptedVaultKey: varchar().notNull().unique(),
    vaultKeyEncryptionNonce: varchar().notNull().unique(),

    updated_at: timestamp().defaultNow().notNull(),
    created_at: timestamp().defaultNow().notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.vaultId, table.userId] }),
    index("vault_members_user_idx").on(table.userId),
  ],
);

export type VaultType = InferSelectModel<typeof vaultsTable>;
export type VaultMemberType = InferSelectModel<typeof vaultMembersTable>;
