/**
 * Bundle drizzle-kit's generated SQL (./drizzle/<timestamp>_<name>/migration.sql)
 * into src/migrations.generated.ts, so the migration runner gets plain strings
 * on every platform (Vite, Metro, Vitest) without bundler-specific SQL imports.
 *
 * Run via `pnpm migrations:generate`, never by hand-editing the output.
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

export type GeneratedMigration = { name: string; statements: string[] };

const STATEMENT_BREAKPOINT = "--> statement-breakpoint";

export function collectMigrations(drizzleDir: string): GeneratedMigration[] {
  return readdirSync(drizzleDir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort()
    .map((name) => ({
      name,
      statements: readFileSync(join(drizzleDir, name, "migration.sql"), "utf8")
        .split(STATEMENT_BREAKPOINT)
        .map((statement) => statement.trim())
        .filter(Boolean),
    }));
}

export function renderModule(migrations: GeneratedMigration[]): string {
  return [
    "// Generated by scripts/bundle-migrations.ts from ./drizzle. Do not edit;",
    "// run `pnpm --filter @repo/store migrations:generate` instead.",
    "",
    `export const GENERATED_MIGRATIONS: readonly { name: string; statements: readonly string[] }[] = ${JSON.stringify(migrations, null, 2)};`,
    "",
  ].join("\n");
}

if (import.meta.main) {
  const root = join(import.meta.dirname, "..");
  const migrations = collectMigrations(join(root, "drizzle"));
  writeFileSync(join(root, "src/migrations.generated.ts"), renderModule(migrations));
  console.log(`Bundled ${migrations.length} migration(s) into src/migrations.generated.ts`);
}
