/**
 * Bundle drizzle-kit's generated SQL (./drizzle/<timestamp>_<name>/migration.sql)
 * into src/migrations.generated.ts (and ./drizzle-registry, the profile
 * registry's, into src/registry-migrations.generated.ts), so the migration runner gets plain strings
 * on every platform (Vite, Metro, Vitest) without bundler-specific SQL imports.
 *
 * Run via `pnpm migrations:generate`, never by hand-editing the output.
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

export type GeneratedMigration = { name: string; statements: string[] };

const STATEMENT_BREAKPOINT = "--> statement-breakpoint";

export function collectMigrations(drizzleDir: string): GeneratedMigration[] {
  return readdirSync(drizzleDir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort()
    .map((name) => ({
      name,
      statements: readFileSync(join(drizzleDir, name, "migration.sql"), "utf8")
        .split(STATEMENT_BREAKPOINT)
        .map((statement) => statement.trim())
        .filter(Boolean),
    }));
}

/** Each bundle: drizzle-kit's output dir → the generated module. */
export const BUNDLES = [
  { drizzleDir: "drizzle", module: "src/migrations.generated.ts" },
  { drizzleDir: "drizzle-registry", module: "src/registry-migrations.generated.ts" },
] as const;

export function renderModule(migrations: GeneratedMigration[], drizzleDir = "drizzle"): string {
  return [
    `// Generated by scripts/bundle-migrations.ts from ./${drizzleDir}. Do not edit;`,
    "// run `pnpm --filter @repo/store migrations:generate` instead.",
    "",
    `export const GENERATED_MIGRATIONS: readonly { name: string; statements: readonly string[] }[] = ${JSON.stringify(migrations, null, 2)};`,
    "",
  ].join("\n");
}

if (import.meta.main) {
  const root = join(import.meta.dirname, "..");
  for (const { drizzleDir, module } of BUNDLES) {
    const migrations = collectMigrations(join(root, drizzleDir));
    writeFileSync(join(root, module), renderModule(migrations, drizzleDir));
    console.log(`Bundled ${migrations.length} migration(s) into ${module}`);
  }
}
