import type { LoginRecord } from "../login-record-schema";

/**
 * Dev seed data: what a real vault looks like, with real websites so icons,
 * search and grouping behave as in daily use. Every credential is made up.
 * Deliberately includes a reused password (Netflix / Spotify / Reddit) and a
 * few weak or old-style ones, as test data for the password-health checks.
 */
export const exampleLoginRecords: LoginRecord[] = [
  {
    title: "GitHub",
    username: "linpark",
    password: "vN7#qT2m!Rx9$kLw4Zp",
    category: "login", // TODO: define categories
    totp: "IZF6XAWJY3QBCZZCGSEG3OWLWZMRJ5XE",
    websites: [{ value: "https://github.com/login" }],
    extraFields: [
      { title: "Recovery codes", type: "secret", value: "4f9a2-c1d7e 88b0f-31a2c 5e6d7-90fa1" },
      { title: "SSH key", type: "text", value: "MacBook Pro (ed25519)" },
    ],
    note: "Personal account. Work org uses SSO.",
  },
  {
    title: "Google",
    username: "lin.park@example.com",
    password: "copper-lantern-orbit-maple",
    category: "login",
    totp: "WO2Z72FZP6PZFRQLS5KY6BFYDIOINCPS",
    websites: [{ value: "https://accounts.google.com" }, { value: "https://mail.google.com" }],
    extraFields: [
      { title: "Backup codes", type: "secret", value: "7421 9983 1057 6620 3148" },
      { title: "Recovery phone", type: "text", value: "+49 151 0000 0000" },
    ],
    note: "",
  },
  {
    title: "Amazon",
    username: "lin.park@example.com",
    password: "Hb8$wqLe2!pZn5",
    category: "login",
    websites: [{ value: "https://www.amazon.de" }, { value: "https://www.amazon.com" }],
    extraFields: [],
    note: "Prime renews in March.",
  },
  {
    title: "Netflix",
    username: "lin.park@example.com",
    password: "Sunflower!2019",
    category: "login",
    websites: [{ value: "https://www.netflix.com/login" }],
    extraFields: [{ title: "Profile PIN", type: "secret", value: "4812" }],
    note: "Shared with family, standard plan.",
  },
  {
    title: "Spotify",
    username: "linpark.music",
    password: "Sunflower!2019",
    category: "login",
    websites: [{ value: "https://accounts.spotify.com" }],
    extraFields: [],
    note: "",
  },
  {
    title: "PayPal",
    username: "lin.park@example.com",
    password: "tR4!mZ8q#Lp2Wv6",
    category: "login",
    totp: "7RUEPI6PV26N57URCIJGOZYWTXWHGGZD",
    websites: [{ value: "https://www.paypal.com/signin" }],
    extraFields: [],
    note: "",
  },
  {
    title: "Apple Account",
    username: "lin.park@example.com",
    password: "Qm9!vX3r$Tn7Lz",
    category: "login",
    websites: [{ value: "https://account.apple.com" }, { value: "https://www.icloud.com" }],
    extraFields: [
      { title: "Security question", type: "text", value: "Name of your first school?" },
      { title: "Answer", type: "secret", value: "Lindenschule" },
    ],
    note: "2FA via trusted devices (iPhone, MacBook).",
  },
  {
    title: "Microsoft (Work)",
    username: "lin.park@acme-corp.example",
    password: "Kd2#pW9x!Mv5Rq8",
    category: "login",
    totp: "YCJADW6FILG43NZ263DNFV2ZLCU3GL3C",
    websites: [
      { value: "https://login.microsoftonline.com" },
      { value: "https://outlook.office.com" },
    ],
    extraFields: [{ title: "Tenant", type: "text", value: "acme-corp" }],
    note: "Password expires every 90 days.",
  },
  {
    title: "Slack",
    username: "lin.park@acme-corp.example",
    password: "Zx7!bN4q$Wm2Pt",
    category: "login",
    websites: [{ value: "https://acme-corp.slack.com" }],
    extraFields: [],
    note: "",
  },
  {
    title: "Notion",
    username: "lin.park@example.com",
    password: "harbor-velvet-sprout-ninety",
    category: "login",
    websites: [{ value: "https://www.notion.so/login" }],
    extraFields: [],
    note: "Personal workspace: recipes, travel plans.",
  },
  {
    title: "Figma",
    username: "lin.park@acme-corp.example",
    password: "Pf6$tQ9m!Xc3Hw",
    category: "login",
    totp: "KIL3TIN73MHMQ7MXKJSOMLGH7C3KUHSL",
    websites: [{ value: "https://www.figma.com/login" }],
    extraFields: [],
    note: "",
  },
  {
    title: "LinkedIn",
    username: "lin.park@example.com",
    password: "Lp3#vR8n!Zq5Km",
    category: "login",
    websites: [{ value: "https://www.linkedin.com/login" }],
    extraFields: [],
    note: "",
  },
  {
    title: "Reddit",
    username: "quiet_lantern",
    password: "Sunflower!2019",
    category: "login",
    websites: [{ value: "https://www.reddit.com/login" }],
    extraFields: [],
    note: "",
  },
  {
    title: "Discord",
    username: "linpark",
    password: "Wn5!kT8x#Rb2Qv",
    category: "login",
    totp: "GXSCBYO2GR7KIBASTJAU7IK7LZZ4GLC2",
    websites: [{ value: "https://discord.com/login" }],
    extraFields: [
      { title: "Backup codes", type: "secret", value: "k2x9-m4p7 q8w1-z6n3 r5t0-b7v2" },
    ],
    note: "",
  },
  {
    title: "Steam",
    username: "quietlantern",
    password: "Gm8#zQ4r!Vt6Np",
    category: "login",
    websites: [
      { value: "https://store.steampowered.com/login" },
      { value: "https://steamcommunity.com" },
    ],
    extraFields: [{ title: "Recovery code", type: "secret", value: "R48213" }],
    note: "Steam Guard via mobile app.",
  },
  {
    title: "Airbnb",
    username: "lin.park@example.com",
    password: "Bt7$wN3q!Lm9Xz",
    category: "login",
    websites: [{ value: "https://www.airbnb.com/login" }],
    extraFields: [],
    note: "",
  },
  {
    title: "Booking.com",
    username: "lin.park@example.com",
    password: "Vr2!qM6x#Tk8Wp",
    category: "login",
    websites: [{ value: "https://account.booking.com/sign-in" }],
    extraFields: [{ title: "Genius level", type: "text", value: "Level 2" }],
    note: "",
  },
  {
    title: "Deutsche Bahn",
    username: "lin.park@example.com",
    password: "zug2014",
    category: "login",
    websites: [{ value: "https://www.bahn.de" }],
    extraFields: [{ title: "BahnCard number", type: "text", value: "7081 4101 0000 0000" }],
    note: "Old account, should update the password.",
  },
  {
    title: "Wikipedia",
    username: "QuietLantern",
    password: "wiki1234",
    category: "login",
    websites: [{ value: "https://en.wikipedia.org/wiki/Special:UserLogin" }],
    extraFields: [],
    note: "",
  },
  {
    title: "AWS Console",
    username: "lin.park",
    password: "Hq9#xR2m!Wv7Tn4Kp",
    category: "login",
    totp: "JSPBCXYJGMFEN32SYR4QGPHB5U6HXU3W",
    websites: [
      { value: "https://signin.aws.amazon.com" },
      { value: "https://console.aws.amazon.com" },
    ],
    extraFields: [
      { title: "Account ID", type: "text", value: "123456789012" },
      { title: "Account alias", type: "text", value: "acme-staging" },
    ],
    note: "IAM user in the staging account. Root credentials are with IT.",
  },
  {
    title: "Dropbox",
    username: "lin.park@example.com",
    password: "Cn4!pZ7w#Qr3Mx",
    category: "login",
    totp: "WXDJOVQYPVLZUX76URGOFQVXOOUXW46S",
    websites: [{ value: "https://www.dropbox.com/login" }],
    extraFields: [],
    note: "",
  },
  {
    title: "FRITZ!Box",
    username: "admin",
    password: "meadow-tractor-quilt-seven",
    category: "login",
    websites: [{ value: "http://fritz.box" }],
    extraFields: [
      { title: "Wi-Fi name", type: "text", value: "Park-Home" },
      { title: "Wi-Fi password", type: "secret", value: "blue-kettle-sunday-42" },
    ],
    note: "Router in the hallway cabinet.",
  },
];

/**
 * Edge cases for QA (seeded only with `devSeed.ts --edge-cases`): odd
 * encodings, empty or oversized fields, invalid TOTP, and injection /
 * phishing payloads the UI must render safely.
 */
export const edgeCaseLoginRecords: LoginRecord[] = [
  {
    title: "Broken TOTP Seed",
    username: "validator.test",
    password: "Test!InvalidTOTP",
    category: "login",
    // Invalid Base32 (contains 1, 8, 9 and symbols)
    totp: "INVALID189TOKEN###",
    websites: [{ value: "https://broken-2fa.example" }],
    extraFields: [{ title: "QA Ticket", type: "text", value: "BUG-2245" }],
    note: "This entry intentionally contains an invalid Base32 TOTP secret.",
  },
  {
    title: "🌍 Unicode Portal Δ",
    username: "søren.测试.🚀",
    password: "Pāsswørd🔥安全",
    category: "login",
    totp: "LINWXLWRJDLIGYCXUFOHBQBH7MTQSRGE",
    websites: [{ value: "https://例子.测试" }],
    extraFields: [
      { title: "Emoji Field 😅", type: "text", value: "🚀🌈✨" },
      { title: "Secret Phrase", type: "secret", value: "π≈3.14159" },
    ],
    note: "Testing full Unicode support across username, password, fields, and domain.",
  },
  {
    title: "Very Long Note Entry",
    username: "documentation.bot",
    password: "LongNote#2026",
    category: "login",
    websites: [{ value: "https://docs.internal.example" }],
    extraFields: [],
    note:
      "This note is intentionally extremely long to test UI overflow behavior, scrolling, database limits, export formatting, and potential truncation issues. " +
      "It repeats content to simulate large encrypted payloads. " +
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. " +
      "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. " +
      "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
  },
  {
    title: "Duplicate Websites Test",
    username: "dup.checker",
    password: "Dup3Check!Pass",
    category: "login",
    websites: [
      { value: "https://duplicate.example" },
      { value: "https://duplicate.example" },
      { value: "https://duplicate.example/login" },
    ],
    extraFields: [{ title: "Environment", type: "text", value: "staging" }],
    note: "Tests deduplication logic and normalization.",
  },
  {
    title: "Empty Everything",
    username: "",
    password: "",
    category: "login",
    totp: "452O6JBTRBUHEQF7Q7BYS5HWWQV6SOPI",
    websites: [],
    extraFields: [],
    note: "",
  },
  {
    title: "Dual 2FA Admin",
    username: "multi.factor.admin",
    password: "Primary!Device#1",
    category: "login",
    totp: "7MOO6NN3CJMBBMPFTQPBI4MXBV4AHYVD",
    websites: [{ value: "https://secure-admin.example" }],
    extraFields: [
      { title: "Backup TOTP", type: "secret", value: "ECZ2ZARELGOOGXQXQ2DVCQYCCTUKDL3B" },
      { title: "Hardware Key ID", type: "text", value: "YUBI-7788-ALPHA" },
    ],
    note: "Primary TOTP in root field, backup stored in extraFields.",
  },
  {
    title: "=CMD|' /C calc'!A0",
    username: "excel.injection",
    password: "CSV!Injection#1",
    category: "login",
    websites: [{ value: "https://spreadsheet-export.example" }],
    extraFields: [
      { title: "Formula Field", type: "text", value: '=HYPERLINK("http://malicious.example")' },
    ],
    note: "Tests CSV/Excel formula injection handling.",
  },
  {
    title: "<script>alert('xss')</script>",
    username: "html.injector",
    password: "DOMPurify!Now",
    category: "login",
    websites: [{ value: "https://ui-render.example" }],
    extraFields: [{ title: "HTML Payload", type: "text", value: "<img src=x onerror=alert(1)>" }],
    note: "<b>Rich text?</b> Or escaped safely?",
  },
  {
    title: "PayPaI Account", // capital i instead of l
    username: "user@secure-paypaI.example",
    password: "PhishMeNot!22",
    category: "login",
    websites: [{ value: "https://secure-paypaI.example" }],
    extraFields: [
      { title: "Security Alert", type: "text", value: "Your account will be suspended!" },
    ],
    note: "Tests homograph / visual phishing detection.",
  },
];
